# Database XEPDB1
# Default username is system
services:
  oracle-xe:
    image: gvenzl/oracle-xe:21-slim
    platform: linux/amd64
    restart: always
    ports:
      - "1521:1521" # Oracle Listener
      - "5500:5500" # Enterprise Manager Express
    environment:
      ORACLE_PASSWORD: "boxlangrocks"
      ORACLE_CHARACTERSET: "AL32UTF8"
    volumes:
      - oracle_data:/opt/oracle/oradata
    shm_size: "1g"

volumes:
  oracle_data:
    driver: local
